#ifndef DEFINES_SHARED_INCLUDED
#define DEFINES_SHARED_INCLUDED
#include "CPPInterop.h"


#define PATHOS_PER_BATCH_SPACE  PATHOS_SHADER_SPACE(0)
#define PATHOS_PER_VIEW_SPACE   PATHOS_SHADER_SPACE(1)
#define PATHOS_PER_FRAME_SPACE  PATHOS_SHADER_SPACE(2)
#define PATHOS_CUSTOM_SPACE     PATHOS_SHADER_SPACE(3)

#endif // DEFINES_SHARED_INCLUDED