cmake_minimum_required(VERSION 3.8)

macro(add_pathos_lib name sources)
    message("Adding pathos engine lib: ${name}")
    add_library(${name} STATIC ${sources})
    target_link_libraries(${name} kt)
    set_target_properties(${name} PROPERTIES FOLDER pathos_libs)
    source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} PREFIX "src" FILES ${sources})
endmacro()

macro(add_pathos_exe name sources)
    message("Adding pathos exe: ${name}")
    add_executable(${name} ${sources})
    target_link_libraries(${name} kt)
    source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} PREFIX "src" FILES ${sources})
endmacro()